# * Project Name: AngelDocs
# * File Name: action.yml
# * Programmer: Kai Prince
# * Date: Sun, Mar 21, 2021
# * Description: This file contains a composite github action.
# *   It will run the documentation generator on the code, then
# *   build a static site.

name: AngelDocs
description: Generate documentation and static site.
branding:
  icon: "book-open"
  color: "white"
inputs:
  project-name:
    description: The name of your project.
    required: true
    default: angel-docs
  files:
    description: The files to process.
    required: true
    default: "**/*.*"
  folder:
    description: The name of the output folder.
    required: true
    default: dist
runs:
  using: docker
  image: Dockerfile
  env:
    FOLDER: ${{ inputs.folder }}
  args:
    - -p ${{ inputs.project-name }} ${{ inputs.files }}
