# * Project Name: AngelDocs
# * File Name: action.yml
# * Programmer: Kai Prince
# * Date: Sun, Mar 21, 2021
# * Description: This file contains a composite github action.
# *   It will run the documentation generator on the code, then
# *   build a static site.

name: AngelDocs
description: Generate documentation and static site.
branding:
  icon: "book-open"
  color: "white"
inputs:
  files: # id of input
    description: Files to process.
    required: true
    default: "**/*"
  folder:
    description: Output folder for site.
    required: true
    default: dist
runs:
  using: docker
  image: Dockerfile
  env:
    FILES: ${{ github.workspace }}/${{ inputs.files }}
    FOLDER: ${{ github.workspace }}/${{ inputs.folder }}
