# This is a basic workflow to help you get started with Actions

name: Generate Documentation

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Run and deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # - uses: KaiPrince/AngelDocs@v0.1
      #   with:
      #     files: src/**/*

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.py') }}
      - name: Install dependencies
        working-directory: src/angel-docs/
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt --upgrade --upgrade-strategy eager; fi
      - name: Run doc generator
        working-directory: src/angel-docs/
        run: |
          python main.py -p angel-docs **/*.py
      - name: Run site generator
        working-directory: docs/
        run: |
          yarn
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/.vitepress/dist # The folder the action should deploy.
